services:
  app:
    build:
      context: .
    image: ros2-devcontainer
    container_name: ros2-devcontainer
    volumes:
      - ../:/ros2_ws/:cached
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    tty: true
    network_mode: 'host'
